### ISSUE TITLE
1.11.2 notes/bugs CHECKLIST - checked are fixed in 1.1.1

### ISSUE THREAD

**Issue by tekkz** [Alex-the-666/Ice_and_Fire#245]
LOVE this mod but just wanted to notify you of some issues I've come across in the most recent 1.11.2 release. To clarify I ran it on single player creative mode the entire time with 0 other mods installed.

- [x] When trying to hatch eggs in water they will duplicate and spit a new one out while the original stays in to hatch. Not sure if intended, seems weird.

- [x] Dragon aggro range is super small it seems. I checked config and didn't see an option to increase it. Perhaps an option in the future? 

- [x] Dead dragons have a tendency to occasionally flop around in place.  Not game breaking, just funny and probably not intended.

- [x] Used command staff and told dragon to stay.  Mounted and flew around for a bit. When I dismounted he teleported back to the "stay" spot.

- [x] When flying a max size dragon (didn't test anything smaller) the dragon and player model shakes and vibrates really fast. Almost like he is glitching through the air. Sometimes he would body roll sideways and I would be riding his chest.  It was only in the air and affected both 1st person and 3rd person.

- [x] Already posted by someone else but I will include it anyways... Tamed dragons don't breathe fire or melee attack.

Again, GREAT mod. I jumped out of my chair in excitement when i saw it ported to 1.11.2. Thanks!

**Comment by Alex-the-666** [comment]
im turning your issue into a checklist as its hard to refrence it as a single issue.

**Comment by tekkz** [comment]
I have not been able to duplicate the egg hatching duplication.  If you are having trouble duplicating anything else let me know, i'd be happy to make a video for you.

**Comment by tekkz** [comment]
In reference to the dead dragons rotating around...

I made a new world and killed a dragon. It only moved while my player model collided with the dragons. Perhaps what I noticed before had something to do with where it died? Maybe there was a neutral mob stuck inside I didnt see? (I doubt the neutral mob was there since I noticed it on multiple dead dragons on the same world)

My money is on the terrain in which the bodies fell. It was not exactly flat.

**Comment by ThatsMyLive** [comment]
This is from the 1.1.1 update:!
**I tried every egg now and got following results on hatching them:**
_Fire dragons:_
Exept the red one, that broke 3 times and dissapeared without spawning a dragon, all others worked out fine with the first try hatching them.

_Ice dragons:_
Silver took 2 times and then hatched.
White immediatly hatched.
Blue hat one try in which it just dropped and didnt even freeze but at secont try hatched.

All three if they froze sometimes dropped themselfes while still being frozen and they all did not hatch after dropping the egg (waited arount 10 MC days).

The only one that I did not manage to hatch was the saphire one, das several times simply dropped and did not even freeze, or if frozen it did the same as the others, dropped a dublicate and then did nothing but stay a block of ice with an egg inside. Not a single one got successfully hatched.

Idk if that could help in any way but I just wanted to bring up my results of hatching tries in case it could be a help! ;)

**Comment by ThatsMyLive** [comment]
So I tried hatching the saphire one once more today and found out a way the frozen eggs do NOT drop a dublicate egg of themself and they are (until now) all 100% hatching if I do this: As soon as the egg froze just stand on top of it and wait for it to hatch. Idk what the dragons think but its kinda funny being like a henn on her eggs and incubating them, haha!

**Comment by AlexModGuy** [comment]
fixed + dupe issues
